eclipse/microprofile-config

README.adoc

fix the code snippet in readme

fix the typo in readme

---

.gitignore
README.adoc
pom.xml

This is the subset of the prior PR addressing IP issues (and fixing https://github.com/microprofile/microprofile-config/issues/10)

Fixed wrong urls in POM and Readme plus license header in Readme

---

api/src/main/java/org/eclipse/microprofile/config/ConfigProvider.java
api/src/main/java/org/eclipse/microprofile/config/spi/ConfigBuilder.java
api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java
api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java
spec/src/main/asciidoc/architecture.asciidoc
spec/src/main/asciidoc/configexamples.asciidoc
spec/src/main/asciidoc/configprovider.asciidoc
spec/src/main/asciidoc/configsources.asciidoc
spec/src/main/asciidoc/converters.asciidoc
spec/src/main/asciidoc/license-alv2.asciidoc
spec/src/main/asciidoc/microprofile-config-spec.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/CustomDbConfigSource.java
tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/SampleYamlConfigSource.java

move the complex and seldom used parts away from ConfigProvider.

#62 configprovider rework

---

api/src/main/java/org/eclipse/microprofile/config/Config.java
api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigProviderTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/CustomConfigSourceTest.java

#54 Change getString to getValue and add getRawString

---

api/src/main/java/org/eclipse/microprofile/config/Config.java

#54 fix javadoc

---

NOTICE

txs to @johnament for reporting!
Signed-off-by: Mark Struberg <struberg@apache.org>
@johnament @Emily-Jiang @OndrejM @gunnarmorling Please check the NOTICE file and if you have something to add. Please also read the Section 4.d of the Apache License before you change something. https://www.apache.org/licenses/LICENSE-2.0

refs: #95 add NOTICE file as required by ALv2.

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java

#99 remove the dynamic changes in this ticket as no consensus was reached

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigBuilder.java
tck/src/main/java/org/eclipse/microprofile/config/tck/AutoDiscoveredConfigSourceTest.java

#119 add one more method on ConfigBuilder to help powerful uses

---

api/src/main/java/org/eclipse/microprofile/config/Config.java

#89 clarify the javadoc on Config

---

api/pom.xml
pom.xml
spec/pom.xml
tck/pom.xml

#132 update the group id and artifact id based on the general consensus

---

NOTICE
README.adoc

Updated Readme based on widest consensus for the term "Feature" in #121 
Plus updating NOTICE file as spoken.
Task-Url: https://github.com/eclipse/microprofile-config/issues/121
Signed-off-by: Werner Keil <werner.keil@gmx.net>

Update Readme #121

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigBuilder.java
api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java
spec/NOTICE
spec/src/main/asciidoc/configexamples.asciidoc
spec/src/main/asciidoc/configprovider.asciidoc
spec/src/main/asciidoc/configsources.asciidoc
spec/src/main/asciidoc/converters.asciidoc
spec/src/main/asciidoc/license-alv2.asciidoc
spec/src/main/asciidoc/microprofile-config-spec.asciidoc
spec/src/main/resources/META-INF/NOTICE
tck/src/main/java/org/eclipse/microprofile/config/tck/AutoDiscoveredConfigSourceTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/CustomDbConfigSource.java
tck/src/main/java/org/eclipse/microprofile/config/tck/converters/Pizza.java
tck/src/main/java/org/eclipse/microprofile/config/tck/converters/PizzaConverter.java

#141 sync up spec doc and refix the #130

---

api/src/main/java/org/eclipse/microprofile/config/Config.java
api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigProviderTest.java
tck/src/main/resources/internal/META-INF/microprofile-config.properties

#139 not spec the limitation as it can be achievable

---

tck/src/main/java/org/eclipse/microprofile/config/tck/CdiOptionalInjectionTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/OptionalValuesBean.java

#145 refract the cts structure to bypass the class duplication

---

api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java
spec/src/main/asciidoc/converters.asciidoc

#151 not force implementator to provide a Date converter

---

api/pom.xml
pom.xml
spec/pom.xml
tck/pom.xml

#153 prepare for 1.0 release

---

tck/src/main/java/org/eclipse/microprofile/config/tck/broken/ConfigOwner.java
tck/src/main/java/org/eclipse/microprofile/config/tck/broken/CustomConverterBean.java
tck/src/main/java/org/eclipse/microprofile/config/tck/broken/MissingConverterOnInstanceInjectionTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/broken/MissingValueOnInstanceInjectionTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/broken/WrongConverterOnInstanceInjectionTest.java

#164 refactor the test class

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java
api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSourceProvider.java

Signed-off-by: Scott Stark <starksm64@gmail.com>

Change the references to javax.config.spi to org.eclipse.microprofile.config.spi

---

site.yaml

This is the same as https://github.com/eclipse/microprofile-config/pull/171 but with the Signed-off-by in the commits.

Individual site config file

---

pom.xml
tck/pom.xml

Updated Arquillian dependency to be consistent with CQ submitted for Eclipse IP review.

Kevin patch arquillian

---

pom.xml

#174 update group id

---

spec/src/main/asciidoc/configexamples.asciidoc

#157 update the example

---

spec/src/main/asciidoc/configsources.asciidoc

#158 update the wording to be environment variables

---

spec/src/main/asciidoc/configprovider.asciidoc

#161 improve configsource spec wording

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigBuilder.java

#161 fix build

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java
tck/src/main/resources/internal/META-INF/microprofile-config.properties

#55 add tck to cover other date format

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java
spec/src/main/asciidoc/configsources.asciidoc

Adding explanation for where this `config_ordinal` applies.

---

tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java

minor tweak tck so that it does not depend on junit at all

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java

fix the offsettime value

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java
tck/src/main/resources/internal/META-INF/microprofile-config.properties

OffsetTime converter is still wrong.

---

spec/src/main/asciidoc/microprofile-config-spec.asciidoc

update spec date and version

---

api/pom.xml
pom.xml
spec/pom.xml
tck/pom.xml

The 1.0 version has been released and marked with the 1.0 tag.
Further development can continue with the new snapshot version.

Switch to version 1.1-SNAPSHOT

---

README.adoc

This might be already clarified elsewhere, but this is a useful place to have it.
Signed-off-by: Mike Croft <mike.croft@payara.fish>

Minor clarification on ordinal precedence.

---

tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java

Adding a TCK test for default property keys on injection points.

---

api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java
spec/src/main/asciidoc/converters.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java
tck/src/main/resources/internal/META-INF/microprofile-config.properties

Adding a built in URL converter.

---

spec/src/main/asciidoc/microprofile-config-spec.asciidoc
tck/running_the_tck.asciidoc

Updating the spec and TCK to reflect 1.1 of MP Config.

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java
spec/src/main/asciidoc/configsources.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigProviderTest.java

Adding a default method for getPropertyNames

---

tck/src/main/java/org/eclipse/microprofile/config/tck/EmptyValuesBean.java
tck/src/main/java/org/eclipse/microprofile/config/tck/EmptyValuesTest.java

This closes #216
Signed-off-by: John D. Ament <johndament@apache.org>

Adding a TCK test that clarifies values being empty as being present.

---

README.adoc

Fixed "rational" to "rationale"

Fixed grammar

---

tck/running_the_tck.asciidoc

Signed-off-by: Scott Stark <starksm64@gmail.com>

Issue#55, add link to example TCK setup

---

api/src/main/java/org/eclipse/microprofile/config/spi/package-info.java

#227 correct package version

---

tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java

#234 update the test to make it more readable and easy to run

---

spec/src/main/asciidoc/configprovider.asciidoc

#217 correct spec to align with APIs

---

api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java
spec/src/main/asciidoc/configprovider.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java

#233 configProperty default name

---

spec/src/main/asciidoc/microprofile-config-spec.asciidoc
spec/src/main/asciidoc/release_notes.asciidoc

Adding release notes for the 1.1 release, based on input from #233

---

README.adoc

This pull-request adds this badge to the README.adoc:
[![Gitter](https://badges.gitter.im/eclipse/microprofile-config.svg)](https://gitter.im/eclipse/microprofile-config)

Add gitter badge

---

README.adoc

Signed-off-by: Jeff Mesnil <jmesnil@gmail.com>

add WildFly/Swarm implementation

---

README.adoc

Signed-off-by: Dominik Heimstädt <dominik.heimstaedt@gmail.com>

Fixed typo in readme.

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigProviderTest.java

fixes #263
Signed-off-by: Matthieu Brouillard <matthieu@brouillard.fr>

remove org.junit.Assert usage

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterTest.java
tck/src/main/resources/internal/META-INF/microprofile-config.properties

@Emily-Jiang this is the pending PR for https://github.com/eclipse/ConfigJSR/pull/35 that fixes the TCK for testing Array conversion/injection

[TCK] Fix ArrayConverterTest

---

api/bnd.bnd

Signed-off-by: arjantijms <arjan.tijms@payara.fish>

#249 Update bnd file to support CDI 1.1 to 2.x

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ImplicitConverterTest.java
tck/src/main/resources/internal/META-INF/microprofile-config.properties

[TCK] add test for implicit Enum converter

---

spec/src/main/asciidoc/converters.asciidoc

#259 correct the escape example

---

spec/src/main/asciidoc/converters.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/ClassConverterTest.java
tck/src/main/resources/internal/META-INF/microprofile-config.properties

Adding spec and TCK to support built in class converters

---

api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java
spec/src/main/asciidoc/converters.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/ImplicitConverterTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/converters/implicit/ConvTestTypeWCharSequenceParse.java
tck/src/main/java/org/eclipse/microprofile/config/tck/converters/implicit/ConvTestTypeWStringValueOf.java
tck/src/main/resources/internal/META-INF/microprofile-config.properties

add parse(CharSequence) support for the implicit converter

---

tck/src/main/java/org/eclipse/microprofile/config/tck/WarPropertiesLocationTest.java

Adding TCK test for property file directly in WAR file (#268)

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ImplicitConverterTest.java

Declare an explicit bean for array types (#287)

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ClassConverterTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ImplicitConverterTest.java

#291 improve test to allow more tck integrators to run

---

pom.xml

update pom.xml to prepare release

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterBean.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterTest.java

improve array tests

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigBuilder.java
api/src/main/java/org/eclipse/microprofile/config/spi/package-info.java

#298 fix package version

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ClassConverterTest.java

[TCK] do not use wildcard in ClassConverterTest

---

api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java
spec/src/main/asciidoc/configexamples.asciidoc
spec/src/main/asciidoc/converters.asciidoc
spec/src/main/asciidoc/release_notes.asciidoc

#302 add MP Config 1.2 release note and further tidy up

---

tck/src/main/java/org/eclipse/microprofile/config/tck/converters/implicit/ConvTestTypeWStringCt.java

Make the string constructor public

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ClassConverterBean.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ClassConverterTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ImplicitConverterTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ParseConverterInjection.java

Move static nested CDI beans out into their own classes

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigProviderTest.java

fixes #310 
Still not a great test

Don't test system props in environment test

---

api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java
spec/src/main/asciidoc/converters.asciidoc

#305 clarify only public constructor used as an implicit converter

---

api/pom.xml
pom.xml
spec/pom.xml
tck/pom.xml

release microprofile config 1.2.1

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java
spec/src/main/asciidoc/configsources.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPropertyNameMatchingTest.java

#264 environment variable mapping rules

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java
spec/src/main/asciidoc/configsources.asciidoc

#264 address review comments

---

api/pom.xml
api/src/main/java/org/eclipse/microprofile/config/Config.java
api/src/main/java/org/eclipse/microprofile/config/package-info.java
api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java
api/src/main/java/org/eclipse/microprofile/config/spi/package-info.java

#321 fix the version changes and enable the baseline

---

tck/src/main/java/org/eclipse/microprofile/config/tck/CdiOptionalInjectionTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/OptionalValuesBean.java

Add an injected Optional<String> property with no property value for it
and should be set to Optional.empty

Fixes #336

---

api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java
spec/src/main/asciidoc/converters.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterBean.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java

This introduces a new built in required URI converter.  This is needed by rest client.
I did a separate commit to clean up the formatting on `ArrayConverterBean`, it was a bit hard to follow.

Uri converter

---

tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPropertyNameMatchingTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/SimpleValuesBean.java
tck/src/main/resources/internal/META-INF/microprofile-config.properties

Fix some minor TCK bugs

---

tck/running_the_tck.asciidoc

* add environment variables requirements to run the TCK

Define env mapping rule

---

spec/src/main/asciidoc/release_notes.asciidoc

#355 create release plan

---

tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPropertyNameMatchingTest.java

#264 remove unused setup

---

api/src/main/java/org/eclipse/microprofile/config/inject/package-info.java

update API version changes due to the changes in #366

---

spec/src/main/asciidoc/converters.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java
tck/src/main/resources/internal/META-INF/microprofile-config.properties

As discussed here's a PR for completing the list of built-in converters. Are there other changes needed than that?

#386 Adding built-in converters for byte, short and char

---

api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java

This reverts commit 4fcbbafcdf7c6eaf32220bd895a2fd7c599c8057.

Revert "Fixes typos"

---

spec/src/main/asciidoc/converters.asciidoc

Nothing fancy, noted while reading the Converters chapter.

Fix a few typos in the Converters section

---

api/src/main/java/org/eclipse/microprofile/config/Config.java
api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java

Use ChronoUnit instead of TimeUnit

---

tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java

Fix TCK error message

---

spec/src/main/asciidoc/configexamples.asciidoc

Signed-off-by: Daniel Dias <daniel.dias.analistati@gmail.com>
See my comments in #415 
thanks,

adjusting configuration via a Java -D system property

---

README.adoc

Signed-off-by: Laird Nelson <ljnelson@gmail.com>

Added microBean MicroProfile Config as an implementation in README.adoc

---

api/src/main/java/org/eclipse/microprofile/config/package-info.java

This fixes https://github.com/eclipse/microprofile-config/issues/394

[#394] Fix ordinal values in Javadoc

---

spec/src/main/asciidoc/architecture.asciidoc
spec/src/main/asciidoc/configexamples.asciidoc
spec/src/main/asciidoc/configprovider.asciidoc
spec/src/main/asciidoc/configsources.asciidoc
spec/src/main/asciidoc/converters.asciidoc
spec/src/main/asciidoc/microprofile-config-spec.asciidoc

#459 Replace Microprofile with MicroProfile in the spec

---

api/pom.xml

#462 restore API version control

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java

Fixes #390
Signed-off-by: David M. Lloyd <david.lloyd@redhat.com>

Do not iterate parent class loaders to find ConfigProviderResolver impls

---

.gitignore
api/pom.xml
pom.xml
tck/pom.xml

#440 exlude EL transitive dependency

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java

#431 rework the configsource api for clarification

---

spec/src/main/asciidoc/configexamples.asciidoc

#404 Add some info regarding passivation capable injection point

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java

Fixes #450
Signed-off-by: David M. Lloyd <david.lloyd@redhat.com>

Use only constant global class loaders to initialize the global resolver

---

api/src/main/java/org/eclipse/microprofile/config/ConfigProvider.java

Prevent incorrect caching of config provider resolver instance

---

api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java
spec/src/main/asciidoc/converters.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/ImplicitConverterTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/converters/implicit/ConvTestSequenceOfBeforeValueOf.java
tck/src/main/java/org/eclipse/microprofile/config/tck/converters/implicit/ConvTestSequenceParseBeforeConstructor.java
tck/src/main/java/org/eclipse/microprofile/config/tck/converters/implicit/ConvTestSequenceValueOfBeforeParse.java
tck/src/main/resources/internal/META-INF/microprofile-config.properties

#383 - change the implicit converter ordering

---

api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java

Signed-off-by: thatsIch <thatsIch@mail.de>

Fixed documentation typo for ConfigProperty

---

spec/src/main/asciidoc/release_notes.asciidoc

(should be 1.4, was pointing to 1.2).

Fixed link pointing to the wrong Milestone

---

.gitignore
api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java
spec/src/main/asciidoc/release_notes.asciidoc

#503 Create a release note for MP Config 1.4

---

README.adoc

Issue #487
Signed-off-by: Ralph Soika <ralph.soika@imixs.com>

changed inlice-code-style into italic-style

---

api/pom.xml

#507 prep for Jenkins build

---

api/pom.xml
pom.xml

#507 fix Jenkins build

---

spec/src/main/asciidoc/release_notes.asciidoc

#503 udpate release note accordingly to remove #365

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java

Escalated from: Using org.junit in TCK tests #516

#516 Removed JUnit assertion from test

---

tck/src/main/java/org/eclipse/microprofile/config/tck/CdiOptionalInjectionTest.java

Signed-off-by: Miguel Serra <Miguel.Serra@criticaltechworks.com>

[#319] Create a test for no defined config value

---

api/pom.xml
pom.xml
tck/pom.xml

#469 rebase against jakarta EE8

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java
api/src/main/java/org/eclipse/microprofile/config/spi/package-info.java
tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/CustomDbConfigSource.java
tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/SampleYamlConfigSource.java

#431 improve configsource api

---

api/src/main/java/org/eclipse/microprofile/config/Config.java
api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java

Clarify rules and guarantees around property name sets

---

api/src/main/java/org/eclipse/microprofile/config/package-info.java

Signed-off-by: Erik Mattheis <erikmattheis@me.com>

Update version to allow API changes

---

api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java
spec/src/main/asciidoc/converters.asciidoc

Follows up #513, follows up #530

Add language to converters spec about additional optional types

---

api/bnd.bnd
api/pom.xml
pom.xml

This is in preparation for future pull requests to improve OSGi metadata.

Update Bnd maven plugins to 5.0.0 and clean up some pom metadata

---

api/src/main/java/org/eclipse/microprofile/config/Config.java
spec/src/main/asciidoc/release_notes.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterBean.java
tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterTest.java
tck/src/main/resources/internal/META-INF/microprofile-config.properties

add multi-value getters to Config

---

api/src/main/java/org/eclipse/microprofile/config/Config.java
api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java
api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java

#555 enable MP Config to be built using Java 11

---

spec/src/main/asciidoc/configexamples.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java

Signed-off-by: Miguel Serra <Miguel.Serra@criticaltechworks.com>

Support Supplier<T> (#220)

---

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java

566: update javadoc on ConfigSource

---

pom.xml

Bnd 5.1.0 has just been released.

deps: Update to use bnd 5.1.0 release

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterTest.java

#549 fix URL equals

---

spec/src/main/asciidoc/configprofile.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/profile/ConfigPropertyFileProfileTest.java

418 - config profile affection on config source level

---

api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java
spec/src/main/asciidoc/converters.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/converters/NullConvertersTest.java

Clarify that nulls cannot be passed in to Converters

---

api/src/main/java/org/eclipse/microprofile/config/ConfigValue.java
spec/src/main/asciidoc/microprofile-config-spec.asciidoc
spec/src/main/asciidoc/property-expressions.asciidoc
spec/src/main/asciidoc/release_notes.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPropertyExpressionsTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/PropertyExpressionsTest.java

Just the initial version to start the discussion. Once we have something that we agree on, I'll move with the TCK
This should handle:
- #118 
- #396

Support Property Expressions.

---

tck/src/main/java/org/eclipse/microprofile/config/tck/CustomConverterTest.java

Signed-off-by: Benjamin Confino <benjamic@uk.ibm.com>
This fixes #599

Add custom converters to test archive

---

spec/src/main/asciidoc/release_notes.asciidoc
tck/running_the_tck.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/DefaultConfigSourceOrdinalTest.java

573: clarify default config source ordinal

---

tck/src/main/java/org/eclipse/microprofile/config/tck/PropertyExpressionsTest.java

Signed-off-by: tevans <tevans@uk.ibm.com>
This is a fix for https://github.com/eclipse/microprofile-config/issues/606

Properly deploy test as Arquillian app

---

api/pom.xml

609 - bring baseline to the latest released version

---

tck/src/main/java/org/eclipse/microprofile/config/tck/PropertyExpressionsTest.java

The tearDown method should release the config which was created by the
test, rather than trying to release the current config for the thread
context classloader.
This change has the side effect of not trying to call
ConfigProviderResolver.instance() from the test process where it may
fail.
Fixes #614

Release the config which was created in PropertyExpressionsTest

---

tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigValueTest.java
tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/DefaultConfigSourceOrdinalTest.java

Correct the Assert.assertEquals on the TCK

---

tck/running_the_tck.asciidoc
tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/DefaultConfigSourceOrdinalTest.java

update tck instructions

---

api/src/main/java/org/eclipse/microprofile/config/Config.java

I made these changes from the Git editor so i'm not sure if i'm merging to/from the correct branch.

Correct typos in Config.java

---

spec/src/main/asciidoc/property-expressions.asciidoc

Fix server.url example in Property Expressions

---

spec/src/main/asciidoc/architecture.asciidoc
spec/src/main/asciidoc/configexamples.asciidoc
spec/src/main/asciidoc/configprovider.asciidoc
spec/src/main/asciidoc/configsources.asciidoc
spec/src/main/asciidoc/converters.asciidoc
spec/src/main/asciidoc/property-expressions.asciidoc
spec/src/main/asciidoc/release_notes.asciidoc

Fixes #637 
Also resolves some other spelling and grammar mistakes in the spec.
Signed-off-by: Joseph Cass <joseph.cass@ibm.com>

Link, spelling, and grammar fixes

---

spec/src/main/asciidoc/release_notes.asciidoc

608: add this issue to the release note

---

pom.xml
spec/pom.xml

644: update spec pdf and html file name

---

pom.xml

644 - tidy up release

---

spec/pom.xml
spec/src/main/asciidoc/microprofile-config-spec.asciidoc

Fixes https://github.com/eclipse/microprofile-config/issues/644

Move deploy to attach artifacts.

---

.github/ISSUE_TEMPLATE/01-compatible-certification-request.md

add CCR template

---

.github/ISSUE_TEMPLATE/01-compatible-certification-request.md

slightly adjust the template labels and title

---

api/pom.xml
api/src/main/javadoc/licenses/Draft/license.html
api/src/main/javadoc/licenses/Final/license.html
pom.xml
spec/pom.xml
spec/src/main/asciidoc/license-efsl.adoc
spec/src/main/asciidoc/microprofile-config-spec.asciidoc

Fix copyright

---

.github/workflows/build.yml

fix workflow java setup

---

api/pom.xml
build-tools/pom.xml
pom.xml
spec/pom.xml
tck/pom.xml

revert failed build due to timeout

---

.github/ISSUE_TEMPLATE/01-compatible-certification-request.md

Also make it visible that implementation need to change the name and version.

Fix typo in certification issue template

---

spec/src/main/asciidoc/configexamples.asciidoc

Signed-off-by: Joseph Cass joseph.cass@ibm.com

Fix code snippet typo in configexamples.asciidoc

---

.github/dependabot.yml

add dependent bot

---

api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperties.java

fix ConfigProperties javadoc

---

spec/src/main/asciidoc/configsources.asciidoc

https://docs.asciidoctor.org/asciidoc/latest/text/troubleshoot-unconstrained-formatting/#use-unconstrained

Fix a formatting issue in the documentation

---

api/pom.xml
pom.xml

Revert the updates done #773 #770 so that the config 3.1 will continue working with EE 9.1.

Revert the updates #773 #770

---

tck/src/main/java/org/eclipse/microprofile/config/tck/profile/OverrideConfigProfileTest.java

Update format to fix build
