eclipse/microprofile-config

api/src/main/java/org/eclipse/microprofile/config/Config.java, api/src/main/java/org/eclipse/microprofile/config/ConfigProvider.java, api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java, api/src/main/java/org/eclipse/microprofile/config/spi/ConfigBuilder.java, api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java, api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java, tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/CustomDbConfigSource.java
=> #41 Add default value in the ConfigProperty

tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java
Assert that an injected property that is not configured in any config
source will use the defaultValue from the annotation.
=> add assertion for defaultValue

tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigProviderTest.java
Part of issue #89.
The test just checks whether it's possible to serialize, deserialize and whether the deserialized object is again a `Config` instance. 
It doesn't check whether it gives any config values - the config values should ideally not be serialized, but retrieved from the runtime environment (especially if it moved to another JVM)
Mark's sample implementation already passes the test.
=> #89 Added test for serializability of injected config

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java
* [api] add ConfigBuilder#addDiscoveredConverters to be able to
discover converters using the ServiceLoader pattern
* [spec] mention new API above and state that converters are not
discovered by default
* [tck] add tests for customer converters
=> Custom converter

spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/microprofile-config-spec.asciidoc
=> Fix warnings when building the spec.

api/pom.xml, pom.xml, tck/pom.xml
Applying fixes to deploy to Maven Central to 1.1-SNAPSHOT version. For 1.0 they aren't stored in the repo because the tag is already created and I didn't want to change the tag.
=> Fixing release for Maven Central

api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java, spec/src/main/asciidoc/converters.asciidoc, tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java
=> Clarify that primitive converts should be built in by default.

.gitignore, perform_release/prepare_release.sh
Signed-off-by: Scott Stark <starksm64@gmail.com>
Hello, while testing this script for a jwt release, I made some change to report on exactly what variable are not defined, and added support to pull these in from a release.conf file that is ignored. Example output when there are missing variable definitions:
```
[microprofile-config 1051]$ cat release.conf 
#RELEASE_VERSION=1.0-RC1
#DEV_VERSION=1.0-SNAPSHOT
GIT_USER='Scott M Stark'
#GIT_EMAIL='starksm64@gmail.com'
[microprofile-config 1052]$ bash perform_release/prepare_release.sh 
RELEASE_VERSION is not defined
DEV_VERSION is not defined
GIT_EMAIL is not defined
ERROR: the following required variables are not defined: RELEASE_VERSION DEV_VERSION GIT_EMAIL
```
I don't know why the last three changes in the the …
=> expand the variable checking and support a release.conf file

pom.xml, spec/pom.xml
The build now generates additional pdf and build artifacts, which can be deployed to a maven repo.
If deployed, they can even be accessed as a maven depepndency, like:
```
<dependency>
<groupId>org.eclipse.microprofile.config</groupId>
<artifactId>microprofile-config-spec</artifactId>
<type>pdf</type>
</dependency>
```
=> Spec module to add pdf and html artifacts

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigBuilder.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/converters/Donald.java, tck/src/main/java/org/eclipse/microprofile/config/tck/converters/UpperCaseDuckConverter.java, tck/src/main/resources/internal/META-INF/microprofile-config.properties
* This method can be used to provide converter using lambda expressions
* add TCK test to check lambda converters
* add TCK text to check priority of lambda and custom converters
=> [API] Add ConfigBuilder#withConverter(Class, int, Converter)

api/pom.xml
=> use config 1.1 as baseline so that more RC can be released

tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java
The UpperCaseDuckConverter needs to be added to the deployed archive so that app server
can properly load it
=> [TCK] add missing UpperCaseDuckConverter

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java
Java 2 permissions are required to get the parent classloader.
=> Use a doPriv to get the parent classloader

pom.xml
This pull requests merely adds a `<links>` element under the `<properties>` element in the `pom.xml` file.  The `maven-javadoc-plugin` defines the `links` user property to contain a comma-separated list of URLs from which `package-list` may be downloaded.  This pull request ensures that https://osgi.org/javadoc/r6/annotation/ is among that list so that OSGi annotations present in the api module will be properly linked in the Javadoc output.
=> Fixes #331 by adding links property

api/src/main/java/org/eclipse/microprofile/config/Config.java, api/src/main/java/org/eclipse/microprofile/config/ConfigProvider.java, api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java, api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java, spec/src/main/asciidoc/configprovider.asciidoc, tck/pom.xml, tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/matchers/AdditionalMatchers.java
Registered converters are applied in getValue() methods. Default config and injected config are equal (plus test). Default config registers discovered converters.
Also renamed test methods from using underscores to camelCase to align to other test code.
Fixes #348.
=> Clarification and test for using converters and injected config

README.adoc
Fix link destination from microprofile-config-spec to microprofile-api.
=> Link to microprofile-config-api in Maven Central

spec/src/main/asciidoc/configexamples.asciidoc
Make it more clear we talk about comma separated list of values. It is not very clear when viewed in PDF. Comma is displayed red and when fast reading somebody might miss the idea.
Signed-off-by: Doychin Bondzhev <doychin@dsoft-bg.com>
=> Make it more clear we talk about comma separated list of values

spec/src/main/asciidoc/configsources.asciidoc
Signed-off-by: Doychin Bondzhev <doychin@dsoft-bg.com>
I've noticed duplicate sentence in the spec for config sources.
=> Remove duplicate sentence 

api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java, api/src/main/java/org/eclipse/microprofile/config/inject/package-info.java, spec/src/main/asciidoc/configexamples.asciidoc, tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java
=> #365 allow null to be injected

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigAccessorTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/ConfigurableConfigSource.java
Update the onAttributeChange method to return a ChangeSupport class that
can be used to handle release of resources (in the close method).
When a Config is released, it should call ChangeSupport.close to ensure
that the ConfigSource has a chance to properly release any resources
held by the callbacks.
* Add TCK test ConfigAccessorTest#testOnAttributeChange
Signed-off-by: Jeff Mesnil <jmesnil@gmail.com>
=> Refactor #384

tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigAccessorTest.java
ConfigurableConfigSource was referenced via the ConfigSource Service Loader but the class was missing from the archive.
=> Add ConfigurableConfigSource.class to tck archive

tck/src/main/java/org/eclipse/microprofile/config/tck/broken/ConfigObserver.java, tck/src/main/java/org/eclipse/microprofile/config/tck/broken/MissingValueOnObserverMethodInjectionTest.java
This pull request adds a test that ensures that observer method injection points are also validated.
Suppose you have this:
private static final void onStartup(@Observes @Initialized(ApplicationScoped.class) final Object event,
@ConfigProperty("this.property.does.not.exist") final String value) {
// do something
}
…you want a `DeploymentException` to be thrown in this case.  I hope this is useful.
Signed-off-by: Laird Nelson <ljnelson@gmail.com>
=> Added a test to the TCK to ensure observer method injection points are also validated

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java, spec/src/main/asciidoc/configsources.asciidoc
List all 3 default ConfigSource first and then add a subsection about
the mapping rule specific to the Env variables.
This fixes #464.
=> [#464] Fix default ConfigSources list

tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterTest.java
`ArrayConverterTest` was missing tests for programmatic lookup over `Config.getOptionalValue(String, Class)`, new testcase with optional was added for every programmatic testcase.
=> Add tests for obtaining arrays over getOptionalValue

spec/src/main/asciidoc/converters.asciidoc
This is a fix for #483 issue in the spec.
Signed-off-by: Ehsan Zaery Moghaddam <zaerymoghaddam@gmail.com>
=> Fixed #483 - Invalid tags used in Automatic Converters section

api/src/main/java/org/eclipse/microprofile/config/Config.java
The API documentation has a typo in which a non-existent `Config::getString` method is mentioned in an example. This PR fixes that.
The incorrect example can be seen in the current [documentation for the Config interface](https://javadoc.io/static/org.eclipse.microprofile.config/microprofile-config-api/1.3/org/eclipse/microprofile/config/Config.html).
=> Adjust documentation on Config interface

pom.xml
To avoid:
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.eclipse.microprofile.config:microprofile-config-api:jar:1.4-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.eclipse.microprofile.maven:microprofile-maven-build-extension is missing. @ org.eclipse.microprofile.config:microprofile-config-parent:1.4-SNAPSHOT, .../pom.xml, line 191, column 21
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.eclipse.microprofile.config:microprofile-config-tck:jar:1.4-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.eclipse.microprofile.maven:microprofile-maven-build-extension is missing. @ org.eclipse.microprofile.config:microprofile-config-parent:1.4-SNAPSHOT, .../pom.xml, line 191, column …
```
=> Set explicit version of plugin

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java
=> #333 javadoc clarification on ConfigSource

tck/src/main/java/org/eclipse/microprofile/config/tck/ImplicitConverterTest.java, tck/src/main/resources/internal/META-INF/microprofile-config.properties
Test was going to always fail due to mismatch between configured value and expected value in test.
=> Fixed assertEquals for testImplicitConverterSquenceOfBeforeValueOf.

api/src/main/java/org/eclipse/microprofile/config/Config.java, api/src/main/java/org/eclipse/microprofile/config/ConfigProvider.java, api/src/main/java/org/eclipse/microprofile/config/package-info.java, api/src/main/java/org/eclipse/microprofile/config/spi/ConfigBuilder.java, api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java, api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java, api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSourceProvider.java, api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java, api/src/main/java/org/eclipse/microprofile/config/spi/package-info.java
This works towards #447 and also will make it easier to specify #448, #426, etc.  No behavior changes are specified in this PR as it is meant purely to clean up the formatting and language, to make it easier for upcoming PRs to cleanly specify behavior changes as needed.
=> Major JavaDoc cleanups, including grammar, structure, style, and content improvements

api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java, api/src/main/java/org/eclipse/microprofile/config/inject/package-info.java, spec/src/main/asciidoc/configexamples.asciidoc, tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java
Revert #388.  This methodology of injecting `null` introduces inconsistencies with the base API:
* It becomes impossible to implement injectable default values with a config source
* It becomes impossible to support a default value with a nullable property
* It introduces another problem case with respect to empty values
* It introduces a problem where injection produces a different result that cannot be replicated on the base API
We need to solve this problem another way. `Optional` is the preferred mechanism, but if we must support nullability on injection, then we should have a separate annotation or annotation property which indicates that the value is optional and there should be an implicit `.orElse(null)`.
=> Revert #388 pending further discussion

spec/src/main/asciidoc/converters.asciidoc
I'm adding a clarification that Converters targeting wrapper primitive types should also be applied to the corresponding primitive types.
Not sure how each implementation is handling this, but I think it makes sense.
Also, it seems there is no TCK for this, so if we agree with this I'll add some.
=> Clarify behaviour of converters for primitive wrappers.

.github/ISSUE_TEMPLATE/00-use-case.md, .github/ISSUE_TEMPLATE/10-clarification.md, .github/ISSUE_TEMPLATE/20-bug-report.md, .github/ISSUE_TEMPLATE/30-impl-proposal.md, .github/ISSUE_TEMPLATE/40-process-change.md, pom.xml
**Description**
This change introduces the usage of GitHub issue templates.  This helps to ensure that each opened issue has exactly one type, and that implementation changes relate back to use cases as discussed previously.
***Footnote***
Please indicate your support for this issue by choosing the :+1: reaction, rather than adding a "+1" or similar comment.
=> Introduce issue templates

api/src/main/java/org/eclipse/microprofile/config/Config.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ClassConverterTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/CustomConverterTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ImplicitConverterTest.java
=> add getConverter method to Config

api/src/main/java/org/eclipse/microprofile/config/spi/ConfigBuilder.java, spec/src/main/asciidoc/configprofile.asciidoc, spec/src/main/asciidoc/configprovider.asciidoc, spec/src/main/asciidoc/microprofile-config-spec.asciidoc, tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/CustomConfigProfileConfigSource.java, tck/src/main/java/org/eclipse/microprofile/config/tck/profile/DevConfigProfileTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/profile/InvalidConfigProfileTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/profile/ProdProfileTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/profile/TestConfigProfileTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/profile/TestCustomConfigProfile.java, tck/src/main/resources/internal/META-INF/microprofile-config.properties
A proposal to support standard way to provide profile-specific properties that would be used only if a profile is specified. This for example enables an application to include configuration for different environments and development stages while only one of them is active (e.g. dev, test, prod).
=> #418 config profile support

api/src/main/java/org/eclipse/microprofile/config/Config.java, api/src/main/java/org/eclipse/microprofile/config/ConfigValue.java, spec/src/main/asciidoc/configexamples.asciidoc, tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigValueTest.java
Here is the initial proposal to support the ConfigValue API in MP Config.
Most likely, we need more detail in the spec, but I didn't want to be really extensive, since all of this is subject to change during revision.
Fixes issues:
https://github.com/eclipse/microprofile-config/issues/43
https://github.com/eclipse/microprofile-config/issues/312
=> ConfigValue API

api/src/main/java/org/eclipse/microprofile/config/Config.java
This is a new proposal to add `unwrap` like proposed previously here:
https://github.com/eclipse/microprofile-config/issues/84
https://github.com/eclipse/microprofile-config/pull/85
I believe the use case is there, especially now where we want to experiment more in the implementation side of things.
=> Added unwrap API to Config.

spec/src/main/asciidoc/configsources.asciidoc
=> #457 add a section to make dynamic config source more visible

spec/src/main/asciidoc/release_notes.asciidoc
=> 582 - add release notes

api/src/main/java/org/eclipse/microprofile/config/Config.java, api/src/main/java/org/eclipse/microprofile/config/ConfigProvider.java, api/src/main/java/org/eclipse/microprofile/config/ConfigValue.java, api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperties.java, api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java, api/src/main/java/org/eclipse/microprofile/config/inject/package-info.java, api/src/main/java/org/eclipse/microprofile/config/package-info.java, api/src/main/java/org/eclipse/microprofile/config/spi/ConfigBuilder.java, api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java, api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java, api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSourceProvider.java, api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java, api/src/main/java/org/eclipse/microprofile/config/spi/package-info.java
There are a lot of changes here, but I didn't modify the content itself.
This work was mostly to make the docs consistent between all sources:
- Removed duplicated empty lines.
- Removed double spaces.
- Wrap at 120 chars.
- Same indentations for li and ol.
- Use paragraphs where required.
- Fixed javadoc warnings.
=> Consistent javadoc formatting

spec/src/main/asciidoc/release_notes.asciidoc
A small typo noticed when reading the release notes. No biggie.
=> Fix typo in the release notes for 2.0

.gitignore, api/src/main/java/org/eclipse/microprofile/config/Config.java, api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSourceProvider.java, spec/src/main/asciidoc/configsources.asciidoc, spec/src/main/asciidoc/release_notes.asciidoc
=> 371 - clarify javadoc on config.getConfigSources

tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPropertyExpressionsTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigPropertiesTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigProviderTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigValueTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/base/AbstractTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/DefaultConfigSourceOrdinalTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/profile/ConfigPropertyFileProfileTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/profile/DevConfigProfileTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/profile/InvalidConfigProfileTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/profile/ProdProfileTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/profile/TestConfigProfileTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/profile/TestCustomConfigProfile.java
Where a test uses beans which are inner classes of the test class,
use a single .war deployment rather than a jar within a war.
This prevents the test beans from being included twice (once in the .jar
and again in the .war).
Fixes #613
=> Avoid duplicate beans in deployments

tck/src/main/java/org/eclipse/microprofile/config/tck/broken/ConfigPropertiesBeanMissingProperty.java, tck/src/main/java/org/eclipse/microprofile/config/tck/broken/ConfigPropertiesMissingPropertyInjectionTest.java
When a deployment uses `ShouldThrowException`, arquillian does not include
the arquillian support classes in the deployed app, including the
`Arquillian` class which the test extends.
In this case, if arquillian is not on the class path on the server, this
test will fail because the test bean cannot be loaded because it depends
on the `Arquillian` class and so doesn't cause the expected deployment
exception.
Fixes #617
=> Move bean out of test class for invalid app test

spec/src/main/asciidoc/release_notes.asciidoc
I'm not sure how to generate a preview of the page, so I have not tested this locally. I just took an example of an internal link from the following: https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configprovider.asciidoc
Fixes #632
=> Fix broken link in Release Notes

api/src/main/java/org/eclipse/microprofile/config/Config.java, api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java, spec/src/main/asciidoc/configexamples.asciidoc, spec/src/main/asciidoc/converters.asciidoc, tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/DefaultConfigSourceOrdinalTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/converters/convertToNull/ConvertedNullValueBrokenInjectionTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/converters/convertToNull/ConvertedNullValueTest.java
=> 608 - nullValue clarification

spec/src/main/asciidoc/configexamples.asciidoc, spec/src/main/asciidoc/release_notes.asciidoc, tck/src/main/java/org/eclipse/microprofile/config/tck/emptyvalue/EmptyValuesTestProgrammaticLookup.java
=> 633 - fix backslack comma behaviour

tck/src/main/java/org/eclipse/microprofile/config/tck/converters/convertToNull/ConvertedNullValueBrokenInjectionBean.java, tck/src/main/java/org/eclipse/microprofile/config/tck/converters/convertToNull/ConvertedNullValueBrokenInjectionTest.java
When a deployment uses ShouldThrowException, arquillian does not include
the arquillian support classes in the deployed app, including the
Arquillian class which the test extends.
In this case, if arquillian is not on the class path on the server, this
test will fail because the test bean cannot be loaded because it depends
on the Arquillian class and so doesn't cause the expected deployment
exception.
Fixes #617 (again)
=> Move bean out of test class in null injection test

pom.xml, tck/pom.xml
Version 8.1.0 removes the use of enum types in the annotations which
avoids compiler warnings for downstream users of the api jar.
We also include osgi.annotation in the tck project to make the
annotation classes available to javadoc to avoid warnings.
=> deps: Update osgi.annotation dependency to 8.1.0

spec/src/main/asciidoc/property-expressions.asciidoc, tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPropertyExpressionsTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/PropertyExpressionsTest.java
fixes #700
The TCK doesn't cover the case where an expression cannot be expanded but the target type is an Optional types or ConfigValue that should not throw `NoSuchElementException`, the goal of this PR is to add new tests to ensure that the expected behavior is consistent. 
* Indicates that in case of ConfigValue, an empty ConfigValue is expected if the expression cannot be expanded.
* Adds new tests to cover this particular use case.
=> Avoid throwing Exception for Optional types and ConfigValue if expression cannot be expanded

tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigPropertiesTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/broken/ConfigPropertiesBeanMissingProperty.java
Fixes #742 
This doesn't change the TCK behavior in any way. It simply makes it CDI-version agnostic so that the TCK works with CDI 3 and CDI 4 implementations. It will ease transition for any early adopters and will eliminate future fraction when actual migration to EE 10 happens. See linked issue for more information.
This change was tested with SR impl customized to run the TCKs on Weld 5 container and the tests passed.
=> Make sure TCKs are CDI-version agnostic

tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java
Avoids adding the InjectionBean into the archive twice, creating
ambiguous resolution errors.
Fixes #748
=> Use a single archive for ConvertersTest

tck/README.adoc
Get TCK running on either CDI 3.0 and CDI 4.0. Update TCK instructions.
=> Update TCK instructions to get TCK running on either CDI 3.0 or 4.0

pom.xml
The version **8.1.0** of `osgi.annotation` removes the use of enum types in the annotations which avoids compiler warnings for downstream users of `microprofile-config-api` jar.
This backports #732 to `3.0.x` branch, which was merged into `master` after the `3.0.x` was branched.
See: #716
See: https://github.com/eclipse/microprofile-config/pull/732#issuecomment-1482128111
See: https://github.com/quarkusio/quarkus/issues/32332
=> Align BND dependencies in 3.0.x to avoid compiler warnings

.github/workflows/build.yml
Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt to temurin to keep receiving software and security updates
See : https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/
=> ci: use actions/setup-java temurin distribution

tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigPropertiesTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigProviderTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/PropertyExpressionsTest.java, tck/src/main/java/org/eclipse/microprofile/config/tck/configsources/DefaultConfigSourceOrdinalTest.java
fixes https://github.com/eclipse/microprofile-config/issues/779
In many cases, when using `Assert.assertEquals`, the expected value argument was first rather than second. While this is correct when using JUnit Assertions, MP Config uses TestNG where the actual value comes first and the expected value is second.
This should make no functional difference to the tests but it will mean that the messages are correct should the test fail.
=> Switch expected and actual values to match TestNG assertEquals

spec/src/main/asciidoc/configprofile.asciidoc, tck/src/main/java/org/eclipse/microprofile/config/tck/profile/OverrideConfigProfileTest.java
Closes #781 
This pull request tries to rephrase parts of the profile on property level spec to clarify how ordinal of sources and the profiled vs. unprofiled values work together.
=> Clarify how source ordinal applies with an active profile

spec/src/main/asciidoc/release_notes.asciidoc, tck/README.adoc
Add the release notes for MP 3.1 release
=> Prepare for the MP 3.1 release

spec/src/main/asciidoc/microprofile-config-spec.asciidoc
The section number on the Release Notes brings confusion with release version number
=> Remove section number from release notes
